run:
  deadline: 5m

# For long-running projects, it will be better to disable all linters, and then selectively enable those you want.
# By default, a minimum of linters is enabled.
# See https://golangci-lint.run/ for details.

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue

linters-settings:
  lll:
    line-length: 160
